"""Field definitions and constants for FMM Tool."""

# People field mapping
PEOPLE_FIELDS = [
    ("Uid", "uid"),
    ("FirstName", "first_name_id"),
    ("LastName", "last_name_id"),
    ("CommonName", "common_name_id"),
    ("DateOfBirth", "dob_raw"),
    ("NationId", "nation_id"),
    ("OtherNationalities", "other_nationalities"),
    ("Ethnicity", "ethnicity"),
    ("Type", "ptype"),
    ("NationalCaps", "national_caps"),
    ("NationalGoals", "national_goals"),
    ("NationalU21Caps", "national_u21_caps"),
    ("NationalU21Goals", "national_u21_goals"),
    ("ClubId", "club_id"),
    ("JoinedDate", "joined_raw"),
    ("Adaptability", "adaptability"),
    ("Ambition", "ambition"),
    ("Controversy", "controversy"),
    ("Loyality", "loyality"),
    ("Pressure", "pressure"),
    ("Professionalism", "professionalism"),
    ("Sportmanship", "sportmanship"),
    ("Temperament", "temperament"),
    ("PlayerId", "player_id"),
    ("DefaultLanguages", "default_languages"),
    ("OtherLanguages", "other_languages"),
    ("Relationships", "relationships"),
]

# Player field mapping
PLAYER_FIELDS = [
    ("Uid", "uid"),
    ("Crossing", "crossing"),
    ("Dribbling", "dribbling"),
    ("Tackling", "tackling"),
    ("Finishing", "finishing"),
    ("LongShot", "longshot"),
    ("Heading", "heading"),
    ("Jumping", "jumping"),
    ("Passing", "passing"),
    ("Decision", "decision"),
    ("Unselfishness", "unselfishness"),
    ("Pace", "pace"),
    ("Strength", "strength"),
    ("Stamina", "stamina"),
    ("Technique", "technique"),
    ("Consistency", "consistency"),
    ("Aggression", "aggression"),
    ("BigMatch", "bigmatch"),
    ("InjuryProne", "injuryprone"),
    ("Leadership", "leadership"),
    ("Versatility", "versatility"),
    ("SetPieces", "setpieces"),
    ("Penalty", "penalty"),
    ("Creativity", "creativity"),
    ("Movement", "movement"),
    ("Positioning", "positioning"),
    ("WorkRate", "workrate"),
    ("Flair", "flair"),
    ("Handling", "handling"),
    ("Kicking", "kicking"),
    ("Agility", "agility"),
    ("Aerial", "aerial"),
    ("Reflexes", "reflexes"),
    ("Communication", "communication"),
    ("Throwing", "throwing"),
    ("GK", "gk"),
    ("LIB", "lib"),
    ("LB", "lb"),
    ("CB", "cb"),
    ("RB", "rb"),
    ("DM", "dm"),
    ("LM", "lm"),
    ("CM", "cm"),
    ("RM", "rm"),
    ("LW", "lw"),
    ("AM", "am"),
    ("RW", "rw"),
    ("CF", "cf"),
    ("LWB", "lwb"),
    ("RWB", "rwb"),
    ("LeftFoot", "leftfoot"),
    ("RightFoot", "rightfoot"),
    ("CA", "ca"),
    ("PA", "pa"),
    ("HomeReputation", "home_rep"),
    ("CurrentReputation", "current_rep"),
    ("WorldReputation", "world_rep"),
    ("InternationalRetirement", "international_retirement"),
    ("SquadNumber", "squad_number"),
    ("PreferredSquadNumber", "preferred_squad_number"),
    ("Height", "height"),
    ("Weight", "weight"),
]

# Nation field mapping
NATION_FIELDS = [
    ("Id", "id"),
    ("Uid", "uid"),
    ("Name", "name"),
    ("Terminator1", "terminator1"),
    ("Nationality", "nationality"),
    ("Terminator2", "terminator2"),
    ("CodeName", "codename"),
    ("ContinentId", "continent_id"),
    ("CapitalId", "capital_id"),
    ("StadiumId", "stadium_id"),
    ("StateOfDevelopment", "state_dev"),
    ("Unknown1", "unknown1"),
    ("Unknown2", "unknown2"),
    ("Region", "region"),
    ("Unknown3", "unknown3"),
    ("Languages", "languages"),
    ("HasMaleTeam", "has_male_team"),
    ("MaleTeam", "male_team"),
    ("HasFemaleTeam", "has_female_team"),
    ("FemaleTeam", "female_team"),
]

# Team subfield mapping
TEAM_SUBFIELDS = [
    ("a", "GameImportance", "game_importance"),
    ("b", "RivalId", "rival_id"),
    ("c", "IsRanked", "is_ranked"),
    ("d", "Ranking", "ranking"),
    ("e", "Points", "points"),
    ("f", "Coefficients", "coefficients"),
    ("g", "Color1", "color1"),
    ("h", "Color2", "color2"),
    ("i", "Color3", "color3"),
    ("j", "Color4", "color4"),
    ("k", "Unknown4", "unknown4"),
    ("l", "Unknown5", "unknown5"),
    ("m", "Unknown6(11bytes HEX)", "unknown6"),
]

# Club field mapping
CLUB_FIELDS = [
    ("Uid", "uid"),
    ("FullName", "full_name"),
    ("ShortName", "short_name"),
    ("SixLetter", "six_letter"),
    ("ThreeLetter", "three_letter"),
    ("BasedId", "based_id"),
    ("NationId", "nation_id"),
    ("Status", "status"),
    ("Academy", "academy"),
    ("Facilities", "facilities"),
    ("AttAvg", "att_avg"),
    ("AttMin", "att_min"),
    ("AttMax", "att_max"),
    ("Reserves", "reserves"),
    ("LeagueId", "league_id"),
    ("Stadium", "stadium"),
    ("LastLeague", "last_league"),
    ("LeaguePos", "league_pos"),
    ("Reputation", "reputation"),
    ("MainClub", "main_club"),
    ("Type", "ctype"),
    ("Gender", "gender"),
    ("Players", "players"),
    ("Affiliates", "affiliates"),
]

# Competition field mapping
COMPETITION_FIELDS = [
    ("Id", "id"),
    ("Uid", "uid"),
    ("FullName", "full_name"),
    ("ShortName", "short_name"),
    ("CodeName", "code_name"),
    ("Type", "ctype"),
    ("ContinentId", "continent_id"),
    ("NationId", "nation_id"),
    ("ForegroundColor", "fg_color"),
    ("BackgroundColor", "bg_color"),
    ("Reputation", "reputation"),
    ("Level", "level"),
    ("ParentCompetitionId", "parent_competition_id"),
    ("Rank1", "rank1"),
    ("Rank2", "rank2"),
    ("Rank3", "rank3"),
    ("Year1", "year1"),
    ("Year2", "year2"),
    ("Year3", "year3"),
    ("Unknown3", "unknown3"),
    ("IsWomen", "is_women"),
    ("Qualifiers", "qualifiers"),
]

# Stadium field mapping
STADIUM_FIELDS = [
    ("Id", "id"),
    ("Uid", "uid"),
    ("CityId", "city_id"),
    ("Capacity", "capacity"),
    ("ExpansionCapacity", "expansion_capacity"),
    ("Name", "name"),
    ("Name2", "name2"),
    ("Terminator", "terminator"),
    ("Unknown3", "unknown3"),
    ("Unknown4", "unknown4"),
]

# Region field mapping
REGION_FIELDS = [
    ("Id", "id"),
    ("Uid", "uid"),
    ("Name", "name"),
    ("Terminator", "terminator"),
    ("NationId", "nation_id"),
    ("WeatherId", "weather_id"),
]

# GACOR preset values
GACOR_STEPS = [
    (6, "58"),
    (8, "5"),
    (16, "20"),
    (17, "20"),
    (18, "20"),
    (20, "20"),
    (21, "20"),
    (25, "76:10"),
    (26, "7:10,10:10,23:10,14:10,9:10,18:10,6:10"),
    (43, "20"),
    (45, "20"),
    (46, "1"),
]
